import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Providers } from "./providers";
import { AuthProvider } from "@/context/AuthContext";
import { SSEProvider } from "@/context/SSEContext";
import { Toaster } from "@/components/ui/sonner";
import SSEStatusIndicator from "@/components/SSEStatusIndicator";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AuthProvider>
            <SSEProvider>
              {children}
            <SSEStatusIndicator />
            </SSEProvider>
          </AuthProvider>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
